#!/opt/homebrew/bin/python3

import requests
import webbrowser
import creds
import iitkgp_erp_login.erp as erp
from iitkgp_erp_login.endpoints import HOMEPAGE_URL

TPSTUDENT_URL = 'https://erp.iitkgp.ac.in/TrainingPlacementSSO/TPStudent.jsp'
headers = {
    'timeout': '20',
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36',
}
session = requests.Session()

_, ssoToken = erp.login(headers, creds, 2, session)

logged_in_url = f"{TPSTUDENT_URL}?ssoToken={ssoToken}"
webbrowser.open(logged_in_url)
