#!/bin/bash

file=$1
f_file=${file}_fmt
shfmt "$file" > "$f_file"

_=$((i = 0))	
if [ -x "$file" ]; then
	_=$((i = 1))	
fi

rm -rf "$file"
mv "$f_file" "$file"

if [ $i == 1 ]; then
	chmod +x "$file"
fi
