#!/bin/bash

latest_videoID=$(curl -s https://www.youtube.com/feeds/videos.xml\?playlist_id\=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg | grep -i videoID | cut -d'<' -f2 | cut -d'>' -f2 | tail -n 1)

if [[ ! -f ~/.100dop ]]; then
	echo "previous_videoID=$latest_videoID" > ~/.100dop
fi
source ~/.100dop


if [ "$latest_videoID" != "$previous_videoID" ]; then
	mpv https://youtu.be/$latest_videoID 
	read -rp "Have you completed today's challenge? [y/n] : " cstatus
	if [[ "$cstatus" == "y" ]]; then
		echo "previous_videoID=$latest_videoID" > ~/.100dop
	fi
else
	echo "You are in-sync with the challenge!"
fi
