#!/bin/bash

# array of directories to check
directories=(
  "/Users/proffapt/Desktop/dotfiles/private"
  "/Users/proffapt/Desktop/dotfiles/public"
  "/Users/proffapt/Desktop/obsidian"
  "/Users/proffapt/.config/nvim/lua/custom"
)

# iterate over directories and check for changes
for dir in "${directories[@]}"; do
  cd "$dir" || exit
  if [ -n "$(git status --porcelain)" ]; then
    git add .
    git commit -m "update"
    git push origin
  fi
done
