#!/opt/homebrew/bin/bash

GIT=/opt/homebrew/bin/git

# array of directories to check
directories=(
  "/Users/proffapt/Desktop/dotfiles/private"
  "/Users/proffapt/Desktop/dotfiles/public"
  "/Users/proffapt/Desktop/obsidian"
  "/Users/proffapt/.config/nvim/lua/custom"
)

# iterate over directories and check for changes
for dir in "${directories[@]}"; do
  cd "$dir" || exit
  if [ -n "$("$GIT" status --porcelain)" ]; then
    "$GIT" add .
    "$GIT" commit -m "update"
    "$GIT" push origin
  fi
done
